### ISSUE TITLE
Cinema experience doesn't work on XBMC Frodo

### ISSUE THREAD

**Issue by asm0dey** [Giftie/script.cinema.experience#6]
Here is what I see in log:

10:43:11 T:2845793088  NOTICE: Thread XBPyThread start, auto delete: false
10:43:11 T:2845793088  NOTICE: -->Python Interpreter Initialized<--
10:43:12 T:2845793088   ERROR: EXCEPTION: Unimplemented method: executehttpapi::executehttpapi(...)
10:43:12 T:2845793088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unimplemented method: executehttpapi::executehttpapi(...)
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.xbmc/addons/script.cinema.experience/addon.py", line 35, in <module>
                                                autorefresh = xbmc.executehttpapi( "GetGuiSetting(1; videoplayer.adjustrefreshrate)" ).replace( "<li>", "" )
                                            RuntimeError: Unimplemented method: executehttpapi::executehttpapi(...)
                                            -->End of Python script error report<--
10:43:15 T:3007244096   ERROR: Control 1 in window 10099 has been asked to focus, but it can't

**Comment by asm0dey** [comment]
Any ideas on this?

**Comment by Giftie** [comment]
Yes, its not Frodo compatible yet.
